### ISSUE TITLE
Detect and yell about event conflicts

### ISSUE THREAD

**Issue by turt2live** [matrix-org/conference-bot#1]
The bot assumes that each `<event />` is a different talk regardless of ID, but doesn't necessarily consider a case of the event potentially spanning two days. If an event were to span two days, it'll either end up with two talk rooms or the first instance will be forgotten - neither of which is a good thing.

p1 to verify if this is a case for the immediate future to worry about.

**Comment by squahtx** [comment]
For FOSDEM 2022, there are no talks crossing midnight UTC or Brussels time:
https://fosdem.org/2022/schedule/roomtracks/

The infodesk event is really a different event on each day, with different IDs, and not some kind of recurring event:
https://fosdem.org/2022/schedule/track/infodesk/
