### ISSUE TITLE
Add commands to allow show management to jump into a wildcard of rooms

### ISSUE THREAD

**Issue by turt2live** [matrix-org/conference-bot#111]
eg: 
* `!conference inviteme *backstage` - all backstage rooms
* `!conference inviteme track M.misc` - all of `M.misc`'s rooms (public, backstage, talks, etc)
* `!conference inviteme talks M.misc` - all of the `M.misc` talks
* `!conference inviteme everything` - the whole thing (talks, backstages, special interest, public)

**Comment by squahtx** [comment]
related: #113
