### ISSUE TITLE
Allow talks with no Q&A to disable it

### ISSUE THREAD

**Issue by kittykat** [matrix-org/conference-bot#119]
so the bot doesn't shout

**Comment by reivilibre** [comment]
@kittykat For WEDF, do *any* of the talks have Q&A? Currently all JSON-schedule talks will have Q&A disabled; I'd have to add in support for Q&A if it's desired.

**Comment by kittykat** [comment]
@reivilibre Sander confirmed no Q&A rooms

**Comment by squahtx** [comment]
see https://github.com/matrix-org/conference-bot/pull/135

**Comment by reivilibre** [comment]
for this year: Q&A availability will be determined by Room ID — `D.*` and `M.test` will have Q&A
