### ISSUE TITLE
Do not create rooms for certain stands

### ISSUE THREAD

**Issue by squahtx** [matrix-org/conference-bot#140]
FOSDEM 2023 will operate in a hybrid mode, running in-person and online at the same time.

Given a stand (`<room name="S.stand_name">` element in the [FOSDEM XML schedule](https://fosdem.org/2022/schedule/xml")), we need a way to determine whether it ought to have an online component. If possible, we'll want the FOSDEM organizers to update the schedule XML to provide that information.

In the spirit of trying to support non-FOSDEM conferences in the future, we could have the pentabarf parser ("backend") filter out non-online stands, so that the rest of the bot is not aware they exist.

Alternatively, we could let the bot create all stands rooms and remove the unwanted ones from the conference space manually.

**Comment by reivilibre** [comment]
2023: Stands will have **no** rooms this year.
