### ISSUE TITLE
Make all space previews work

### ISSUE THREAD

**Issue by squahtx** [matrix-org/conference-bot#142]
To make space previews work, `m.room.guest_access` `{guest_access: "can_join"}` and `m.room.history_visibility` `{history_visibility: "world_readable"}` events need to be sent in all (sub)spaces.

This was partially done in https://github.com/matrix-org/conference-bot/pull/88, but that PR neglected to set `m.room.guest_access` for auditorium subspaces.

TODO: check if `m.room.history_visibility` is actually required to make space previews work.

**Comment by reivilibre** [comment]
@squahtx Do you know why `m.room.guest_access` is needed? I'm looking through Synapse (and the spec... which is underspecified :/) and can't see where it comes into play.

**Comment by squahtx** [comment]
I can't remember, I'm afraid. It may be to satisfy logic on Element Web?

**Comment by turt2live** [comment]
Guest access allows anonymous viewers to view the room, as they otherwise would get told to go away (slightly awkward because an authenticated user could see the room, but guest users would be declined 🤷 )

**Comment by reivilibre** [comment]
agh, it doesn't do custom state events indeed, boo :(
