### ISSUE TITLE
chat.fosdem.org (element-web/develop) doesn't redirect to mobile correctly when not logged in

### ISSUE THREAD

**Issue by benparsons** [matrix-org/conference-bot#27]
> Will there be a link to an associated Matrix room attached to each event in Pentabarf? 
> If not, what's the correct link format to join a specific room? Linking to https://chat.fosdem.org/#/room/#containers:fosdem.org works, but+ only when I am already logged-in. Also perhaps there's a link that can open an app on mobile if available.

https://matrix.to/#/!lPCpzTqvUEAAXpOVzt:fosdem.org/$6y3skPMV6C65SwVfb3BnZ1mbTwNsU8kYNN0o-ID5OFg?via=fosdem.org&via=matrix.org&via=privacytools.io

**Comment by turt2live** [comment]
moved to https://github.com/vector-im/element-web/issues/16283
