### ISSUE TITLE
Persist scoreboard

### ISSUE THREAD

**Issue by turt2live** [matrix-org/conference-bot#28]
If the bot restarts then it loses track of all of the scoreboard data. It should persist it somewhere in case it is restarted. 

Specifically:
* What is currently on the scoreboard
* What the vote count is (though this can be retrieved from the server with `/aggregations`)

**Comment by squahtx** [comment]
Closing this.

As noted by Travis, the bot resumes syncing from where it left off, so the chance of missing a vote is minimal except for one
corner case, which has been filed as #92.
