### ISSUE TITLE
Support "stands" and other misc rooms

### ISSUE THREAD

**Issue by turt2live** [matrix-org/conference-bot#4]
For stands, interest groups, etc in the conference. 

* [ ] "Special Interest" room imports
* [ ] Handle infodesk as a special room (own flair)

**Comment by squahtx** [comment]
It looks like this functionality has already been added in 7a485cfd26dc85f78d9b2550e3375e467b722136 .

todo: test it and confirm it works as desired for FOSDEM 2022.

**Comment by squahtx** [comment]
Seems to work great.
