### ISSUE TITLE
Show clear indication when live streaming is on

### ISSUE THREAD

**Issue by kittykat** [matrix-org/conference-bot#44]
As a presenter or moderator, I want to know when the call/stream I am in is live so that I am aware that it is being broadcast.

In addition to [countdown leading up to livestream](https://github.com/matrix-org/conference-bot/issues/12), I would like to be able to tell the state easily.

This could be achieved with an overlay in the video which has a red indicator that tells me that the video is live (e.g. "LIVE" in a pill-style bubble in the corner of the video).

**Comment by squahtx** [comment]
Currently there's always a "You are being live broadcasted" indicator while in the Jitsi for a talk. It'll need to take into account the Q&A start time.
