### ISSUE TITLE
Module to bridge moderators between Jitsi and Matrix room

### ISSUE THREAD

**Issue by kittykat** [matrix-org/conference-bot#47]
Talk moderators should be able to moderate both the Jisti stream so it would make sense to sync moderators from room to Jitsi

**Comment by kittykat** [comment]
ToDo: ask Ops if this is their domain

**Comment by benbz** [comment]
This is https://github.com/matrix-org/prosody-mod-auth-matrix-user-verification#mod_matrix_power_sync which is deployed with FOSDEM's Jitsi stack. Let us know if it doesn't seem to be working correctly

**Comment by kittykat** [comment]
@benbz during testing on Monday, it wasn't obvious if moderators were being bridged (I was a moderator in the room and didn't see anything change in Jitsi to allow me to moderate so it looks like it's not working right at the moment

**Comment by benbz** [comment]
> @benbz during testing on Monday, it wasn't obvious if moderators were being bridged (I was a moderator in the room and didn't see anything change in Jitsi to allow me to moderate so it looks like it's not working right at the moment

Would it be possible to run some tests on this soon? We don't have logs from Monday's tests

**Comment by benbz** [comment]
After a diversion into fixing another issue with the Jitsi stack (secrets getting out of sync) the issue should be resolved with https://github.com/matrix-org/docker-jitsi-meet/pull/14. The matrix power sync module wasn't being loaded in the correct place. Sean and I did some quick testing and the correct people were moderated and no-one unexpected got turned into a moderator one the lasts moderator leaving
