### ISSUE TITLE
Give moderators permission to remove the hybrid widget in the talk room once the talk is over so they can leave

### ISSUE THREAD

**Issue by kittykat** [matrix-org/conference-bot#49]
Moderators should be able to control the widgets in their rooms so that they can remove widgets when talks finish so that the moderator can leave.

**Comment by kittykat** [comment]
ToDo: follow up with Travis to clarify this requirement

**Comment by squahtx** [comment]
Set widget permissions to moderator when the talk ends.

**Comment by squahtx** [comment]
Moderators can already remove widgets from talk rooms at any time.
