### ISSUE TITLE
Make users join Jitsi room muted by default

### ISSUE THREAD

**Issue by kittykat** [matrix-org/conference-bot#50]
We don't want everyone to be unmuted by default as it will affect the quality of the stream and flow of Q&A. Force all users to join the Jitsi rooms on mute by default.

**Comment by squahtx** [comment]
Do we want to turn off video by default too?

**Comment by kittykat** [comment]
> Do we want to turn off video by default too?

I think mic muted and camera on because ideally we want people to have a video stream
