### ISSUE TITLE
Popping out widget and maximising it does not change audio settings

### ISSUE THREAD

**Issue by kittykat** [matrix-org/conference-bot#51]
Audio settings should remain the same regardless of how the user interacts with widget location or sizing.

(This needs to be tested to confirm that this is still an issue)

**Comment by squahtx** [comment]
I'm assuming this is about the video player and not Jitsi.  
Popping out the widget loads a completely new instance of the widget, which is why it resets. We might be able to remember the audio settings in `localStorage`.

**Comment by squahtx** [comment]
`localStorage` only works while third party tracking is allowed, and only works for maximise.

Leaving this issue alone for now.

**Comment by squahtx** [comment]
Filed the maximise issue as https://github.com/vector-im/element-web/issues/20596

**Comment by kittykat** [comment]
Assigning to @jaywink as this has been fixed upstream and we just need to make sure it makes it into our downstream app

**Comment by kittykat** [comment]
Fixed
