### ISSUE TITLE
Create devroom-managers room for FOSDEM and invite all devroom coordinators

### ISSUE THREAD

**Issue by kittykat** [matrix-org/conference-bot#73]
The bot should create a #devroom-managers room and invite all devroom coordinators during setup (follow existing workflow for invites).

**Comment by squahtx** [comment]
nb: `D.*` devroom coordinators only, not `M.*`, `K.*` or `L.*`

**Comment by ShinIce** [comment]
Please exclude also S.*

**Comment by squahtx** [comment]
This was set as `conference.supportRooms.coordinators` last year. The bot needs to be updated to only invite D.* coordinators and not the rest.

**Comment by squahtx** [comment]
Done in #78.
